server:
  port: 9000

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
      # routes mapping for event-store-service
      - id: EVENT-STORE-SERVICE
        uri: http://localhost:8081
        predicates:
          - Path=/api/employee/**

      # routes mapping for employee-attendance-process-service
      - id: employee-attendance-process-service
        uri: http://localhost:8082/
        predicates:
          - Path=/api/process/**